const PDFDocument = require('pdfkit');
const XLSX = require('xlsx');
const path = require('path');

/**
 * Generate Excel Report Buffer
 * @param {Array} data - Array of credit objects
 * @param {Object} metadata - { level, title, date, generatedBy }
 * @returns {Buffer}
 */
function createExcelReport(data, metadata, view = 'transactions') {
  const wb = XLSX.utils.book_new();

  // 1. Summary Sheet
  const summaryData = [
    ['Report Title', metadata.title],
    ['Report Type', view === 'ranking' ? 'FACULTY RANKING (AGGREGATED)' : 'TRANSACTION DETAILS'],
    ['Level', metadata.level.toUpperCase()],
    ['Generated At', metadata.date],
    ['Generated By', metadata.generatedBy || 'N/A'],
    ['Total Records', data.length],
    [],
    ['Note', 'This report is computer generated from the Faculty Credit System.']
  ];
  const summaryWs = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary');

  // 2. Data Sheet
  let details;
  if (view === 'ranking') {
    details = data.map(item => ({
      'Faculty ID': item.facultyID || 'N/A',
      'Name': item.name || 'N/A',
      'Department': item.department || 'N/A',
      'Positive Credits': item.positive || 0,
      'Negative Credits': item.negative || 0,
      'Total Net Credits': item.total || 0,
      'Activity Count': item.count || 0
    }));
  } else {
    details = data.map(item => ({
      'Faculty ID': item.facultySnapshot?.facultyID || 'N/A',
      'Faculty Name': item.facultySnapshot?.name || 'N/A',
      'Department': item.facultySnapshot?.department || 'N/A',
      'Type': item.type?.toUpperCase() || 'N/A',
      'Title': item.title || 'N/A',
      'Points': item.points || 0,
      'Academic Year': item.academicYear || 'N/A',
      'Status': item.status || 'N/A',
      'Date': new Date(item.createdAt).toLocaleDateString()
    }));
  }
  const detailsWs = XLSX.utils.json_to_sheet(details);
  XLSX.utils.book_append_sheet(wb, detailsWs, view === 'ranking' ? 'Ranking' : 'Details');

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

/**
 * Generate PDF Report Buffer
 * @param {Array} data - Array of credit objects
 * @param {Object} metadata - { level, title, date, generatedBy }
 * @returns {Promise<Buffer>}
 */
function createPdfReport(data, metadata, view = 'transactions') {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        margin: 50, 
        size: 'A4',
        bufferPages: true 
      });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
          doc.switchToPage(i);
          const footerY = doc.page.height - 50;
          doc.moveTo(50, footerY).lineTo(545, footerY).strokeColor('#e2e8f0').lineWidth(0.5).stroke();
          doc.fontSize(7).fillColor('#718096');
          doc.text(`CreditWise - ${metadata.generatedBy} / ${metadata.date}`, 50, footerY + 10, { width: 200, align: 'left' });
          doc.text('This is System Generated Report', 50, footerY + 10, { width: 495, align: 'center' });
          doc.text(`Page | ${i + 1}`, 345, footerY + 10, { width: 200, align: 'right' });
        }
        resolve(Buffer.concat(buffers));
      });

      const logoPath = path.join(__dirname, '../public/egs-pillay-group-logo-flat-dark.png');
      const drawHeader = () => {
        doc.rect(0, 0, doc.page.width, 95).fill('#ffffff');
        try { doc.image(logoPath, 50, 35, { height: 35 }); } catch(e) { 
          doc.fontSize(16).font('Helvetica-Bold').fillColor('#001b70').text('EGSPGOI', 50, 45); 
        }
        doc.fontSize(22).font('Helvetica-Bold').fillColor('#001b70').text('CreditWise', 350, 42, { align: 'right', width: 195 });
        doc.moveTo(50, 85).lineTo(545, 85).strokeColor('#001b70').lineWidth(2).stroke();
      };

      drawHeader();
      doc.y = 110;

      // --- Title Section ---
      doc.fillColor('#1a202c').fontSize(18).font('Helvetica-Bold').text(metadata.title, { align: 'left' });
      doc.fontSize(9).font('Helvetica').fillColor('#718096').text(`Scope: ${metadata.level.toUpperCase()}  |  Report Type: ${view.toUpperCase()}  |  Generated by: ${metadata.generatedBy}`);
      doc.moveDown(1.5);

      // --- Summary Analytics Panel ---
      const analyticsY = doc.y;
      doc.rect(50, analyticsY, 495, 60).fill('#f8fafc');
      doc.rect(50, analyticsY, 495, 60).strokeColor('#e2e8f0').lineWidth(1).stroke();

      const drawStat = (label, value, x, y) => {
        doc.fillColor('#4a5568').fontSize(8).font('Helvetica-Bold').text(label.toUpperCase(), x, y);
        doc.fillColor('#1a202c').fontSize(12).font('Helvetica-Bold').text(String(value), x, y + 12);
      };

      if (view === 'ranking') {
        const avgCredit = data.length ? (data.reduce((s, i) => s + i.total, 0) / data.length).toFixed(1) : 0;
        drawStat('Total Faculty', data.length, 70, analyticsY + 15);
        drawStat('Avg Net Credit', avgCredit, 190, analyticsY + 15);
        drawStat('Top Score', Math.max(...data.map(i => i.total), 0), 330, analyticsY + 15);
        drawStat('Low Score', Math.min(...data.map(i => i.total), 0), 450, analyticsY + 15);
      } else {
        const totalPoints = data.reduce((sum, item) => sum + (item.points || 0), 0);
        drawStat('Total Activities', data.length, 70, analyticsY + 15);
        drawStat('Cumulative Points', totalPoints, 190, analyticsY + 15);
        drawStat('Positive Credits', data.filter(c => c.type === 'positive').length, 330, analyticsY + 15);
        drawStat('Negative Credits', data.filter(c => c.type === 'negative').length, 450, analyticsY + 15);
      }

      doc.y = analyticsY + 85;

      // --- Table Construction ---
      let colWidths, colPos, headers;
      if (view === 'ranking') {
        colWidths = { name: 180, dept: 125, pos: 60, neg: 60, total: 70 };
        colPos = { name: 50, dept: 230, pos: 355, neg: 415, total: 475 };
        headers = ['FACULTY NAME & ID', 'DEPARTMENT', 'POS (+)', 'NEG (-)', 'NET TOTAL'];
      } else {
        colWidths = { date: 65, faculty: 110, activity: 220, type: 60, points: 40 };
        colPos = { date: 50, faculty: 115, activity: 225, type: 445, points: 505 };
        headers = ['DATE', 'FACULTY & ID', 'ACTIVITY DETAILS', 'TYPE', 'POINTS'];
      }

      const drawTableHeader = (y) => {
        doc.rect(50, y, 495, 25).fill('#001b70');
        doc.fillColor('#ffffff').fontSize(8).font('Helvetica-Bold');
        if (view === 'ranking') {
          doc.text(headers[0], colPos.name + 5, y + 9);
          doc.text(headers[1], colPos.dept + 5, y + 9);
          doc.text(headers[2], colPos.pos, y + 9, { width: colWidths.pos, align: 'center' });
          doc.text(headers[3], colPos.neg, y + 9, { width: colWidths.neg, align: 'center' });
          doc.text(headers[4], colPos.total, y + 9, { width: colWidths.total, align: 'center' });
        } else {
          doc.text(headers[0], colPos.date + 5, y + 9);
          doc.text(headers[1], colPos.faculty + 5, y + 9);
          doc.text(headers[2], colPos.activity + 5, y + 9);
          doc.text(headers[3], colPos.type + 5, y + 9);
          doc.text(headers[4], colPos.points, y + 9, { align: 'center', width: colWidths.points });
        }
      };

      drawTableHeader(doc.y);
      let rowY = doc.y + 25;

      data.forEach((item, index) => {
        let rowHeight = 40;
        let text1, text2, text3, val1, val2, totalVal;

        if (view === 'ranking') {
          text1 = `${item.name}\nID: ${item.facultyID}`;
          text2 = item.department;
          val1 = String(item.positive || 0);
          val2 = String(item.negative || 0);
          totalVal = String(item.total || 0);
          const h1 = doc.heightOfString(text1, { width: colWidths.name - 10 });
          rowHeight = Math.max(35, h1 + 15);
        } else {
          text1 = new Date(item.createdAt).toLocaleDateString();
          text2 = `${item.facultySnapshot?.name || 'N/A'}\nID: ${item.facultySnapshot?.facultyID || 'N/A'}`;
          text3 = item.title || 'N/A';
          val1 = item.type?.toUpperCase() || 'N/A';
          val2 = String(item.points || 0);
          const h2 = doc.heightOfString(text2, { width: colWidths.faculty - 10 });
          const h3 = doc.heightOfString(text3, { width: colWidths.activity - 10 });
          rowHeight = Math.max(40, h2 + 15, h3 + 15);
        }

        if (rowY + rowHeight > 750) {
          doc.addPage();
          drawHeader();
          drawTableHeader(105);
          rowY = 130;
        }

        if (index % 2 !== 0) doc.rect(50, rowY, 495, rowHeight).fill('#f9fafb');
        
        doc.fillColor('#2d3748').font('Helvetica').fontSize(8.5);
        if (view === 'ranking') {
          doc.text(text1, colPos.name + 5, rowY + 12, { width: colWidths.name - 10 });
          doc.text(text2, colPos.dept + 5, rowY + 12, { width: colWidths.dept - 10 });
          doc.fillColor('#059669').text(val1, colPos.pos, rowY + 12, { width: colWidths.pos, align: 'center' });
          doc.fillColor('#dc2626').text(val2, colPos.neg, rowY + 12, { width: colWidths.neg, align: 'center' });
          doc.fillColor('#1a202c').font('Helvetica-Bold').text(totalVal, colPos.total, rowY + 12, { width: colWidths.total, align: 'center' });
        } else {
          doc.text(text1, colPos.date + 5, rowY + 12);
          doc.text(text2, colPos.faculty + 5, rowY + 12, { width: colWidths.faculty - 10 });
          doc.text(text3, colPos.activity + 5, rowY + 12, { width: colWidths.activity - 10 });
          doc.fillColor(item.type === 'positive' ? '#059669' : '#dc2626').font('Helvetica-Bold').text(val1, colPos.type + 5, rowY + 12);
          doc.fillColor('#1a202c').text(val2, colPos.points, rowY + 12, { width: colWidths.points, align: 'center' });
        }

        doc.moveTo(50, rowY + rowHeight).lineTo(545, rowY + rowHeight).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
        rowY += rowHeight;
      });

      doc.end();
    } catch (err) { reject(err); }
  });
}

/**
 * Generate HTML Report (Landing Page)
 * @param {Array} data - Array of credit objects
 * @param {Object} metadata - { level, title, date }
 * @param {Object} links - { pdf, excel }
 * @returns {string} - HTML string
 */
function createHtmlReport(data, metadata, links, view = 'transactions') {
  const isRanking = view === 'ranking';
  
  const headers = isRanking 
    ? `<tr><th>Faculty</th><th>Department</th><th>Pos (+)</th><th>Neg (-)</th><th>Net Total</th><th>Activities</th></tr>`
    : `<tr><th>Date</th><th>Faculty</th><th>Activity</th><th>Type</th><th>Pts</th><th>Status</th></tr>`;

  const rows = data.map(item => {
    if (isRanking) {
      return `
        <tr>
          <td>${item.name}<br><small>${item.facultyID}</small></td>
          <td>${item.department}</td>
          <td style="color: #38a169;">+${item.positive}</td>
          <td style="color: #e53e3e;">-${item.negative}</td>
          <td><strong>${item.total}</strong></td>
          <td>${item.count}</td>
        </tr>
      `;
    }
    return `
      <tr>
        <td>${new Date(item.createdAt).toLocaleDateString()}</td>
        <td>${item.facultySnapshot?.name || 'N/A'}<br><small>${item.facultySnapshot?.facultyID || 'N/A'}</small></td>
        <td>${item.title || 'N/A'}</td>
        <td class="type-${item.type}">${item.type?.toUpperCase() || 'N/A'}</td>
        <td><strong>${item.points || 0}</strong></td>
        <td><span class="status-${item.status}">${item.status?.toUpperCase() || 'N/A'}</span></td>
      </tr>
    `;
  }).join('');

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${metadata.title}</title>
      <style>
        body { font-family: 'Inter', system-ui, -apple-system, sans-serif; line-height: 1.5; color: #1a202c; background: #f7fafc; margin: 0; padding: 2rem; }
        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 2rem; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }
        header { border-bottom: 2px solid #edf2f7; margin-bottom: 2rem; padding-bottom: 1rem; display: flex; justify-content: space-between; align-items: flex-end; }
        h1 { margin: 0; color: #2d3748; font-size: 1.5rem; }
        .meta { color: #718096; font-size: 0.875rem; }
        .actions { display: flex; gap: 0.75rem; margin-bottom: 1.5rem; }
        .btn { padding: 0.5rem 1rem; border-radius: 6px; text-decoration: none; font-weight: 600; font-size: 0.875rem; transition: all 0.2s; border: 1px solid transparent; }
        .btn-pdf { background: #e53e3e; color: white; }
        .btn-pdf:hover { background: #c53030; }
        .btn-excel { background: #38a169; color: white; }
        .btn-excel:hover { background: #2f855a; }
        table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
        th { text-align: left; background: #edf2f7; padding: 0.75rem; font-size: 0.875rem; text-transform: uppercase; color: #4a5568; }
        td { padding: 10px; border-bottom: 1px solid #edf2f7; font-size: 0.9375rem; }
        .type-positive { color: #38a169; font-weight: bold; }
        .type-negative { color: #e53e3e; font-weight: bold; }
        .status-approved { background: #c6f6d5; color: #22543d; padding: 2px 8px; border-radius: 9999px; font-size: 0.75rem; }
        .status-pending { background: #feebc8; color: #744210; padding: 2px 8px; border-radius: 9999px; font-size: 0.75rem; }
        footer { margin-top: 2rem; text-align: center; color: #a0aec0; font-size: 0.75rem; }
        @media (max-width: 640px) { body { padding: 1rem; } .container { padding: 1rem; } header { flex-direction: column; align-items: flex-start; gap: 1rem; } }
      </style>
    </head>
    <body>
      <div class="container">
        <header>
          <div>
            <h1>${metadata.title}</h1>
            <div class="meta">Level: ${metadata.level} | Type: ${view.toUpperCase()} | Generated: ${metadata.date}</div>
          </div>
          <div class="actions">
            <a href="${links.pdf}" class="btn btn-pdf">Download PDF</a>
            <a href="${links.excel}" class="btn btn-excel">Download Excel</a>
          </div>
        </header>
        
        <div style="overflow-x: auto;">
          <table>
            <thead>
              ${headers}
            </thead>
            <tbody>
              ${rows}
            </tbody>
          </table>
        </div>

        <footer>
          This is a live report generated from the Faculty Credit System. 
          The data shown is current as of the time of generation.
        </footer>
      </div>
    </body>
    </html>
  `;
}

module.exports = { createExcelReport, createPdfReport, createHtmlReport };
