const PDFDocument = require('pdfkit');
const XLSX = require('xlsx');
const path = require('path');

/**
 * Generate Excel Report Buffer
 * @param {Array} data - Array of credit objects
 * @param {Object} metadata - { level, title, date, generatedBy }
 * @returns {Buffer}
 */
function createExcelReport(data, metadata) {
  const wb = XLSX.utils.book_new();

  // 1. Summary Sheet
  const summaryData = [
    ['Report Title', metadata.title],
    ['Level', metadata.level.toUpperCase()],
    ['Generated At', metadata.date],
    ['Generated By', metadata.generatedBy || 'N/A'],
    ['Total Records', data.length],
    ['Total Points', data.reduce((sum, item) => sum + (item.points || 0), 0)],
    [],
    ['Note', 'This report is computer generated from the Faculty Credit System.']
  ];
  const summaryWs = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary');

  // 2. Details Sheet
  const details = data.map(item => ({
    'Faculty ID': item.facultySnapshot?.facultyID || 'N/A',
    'Faculty Name': item.facultySnapshot?.name || 'N/A',
    'Department': item.facultySnapshot?.department || 'N/A',
    'Type': item.type?.toUpperCase() || 'N/A',
    'Title': item.title || 'N/A',
    'Points': item.points || 0,
    'Academic Year': item.academicYear || 'N/A',
    'Status': item.status || 'N/A',
    'Date': new Date(item.createdAt).toLocaleDateString()
  }));
  const detailsWs = XLSX.utils.json_to_sheet(details);
  XLSX.utils.book_append_sheet(wb, detailsWs, 'Details');

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

/**
 * Generate PDF Report Buffer
 * @param {Array} data - Array of credit objects
 * @param {Object} metadata - { level, title, date, generatedBy }
 * @returns {Promise<Buffer>}
 */
function createPdfReport(data, metadata) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        margin: 50, 
        size: 'A4',
        bufferPages: true 
      });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        // Add footers and finalize
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
          doc.switchToPage(i);
          
          // Subtle line above footer
          doc.moveTo(50, doc.page.height - 50).lineTo(545, doc.page.height - 50).strokeColor('#e2e8f0').lineWidth(0.5).stroke();

          // Footer Text
          doc.fontSize(8).fillColor('#718096')
             .text(`CreditWise - ${metadata.generatedBy} / ${metadata.date} / EGSPGOI`, 50, doc.page.height - 40, { align: 'left' });
          doc.text(`Page | ${i + 1}`, doc.page.width - 150, doc.page.height - 40, { align: 'right' });
        }
        resolve(Buffer.concat(buffers));
      });

      const logoPath = path.join(__dirname, '../public/egs-pillay-group-logo-flat-dark.png');
      
      const drawHeader = () => {
        // Left Logo
        try {
          doc.image(logoPath, 50, 45, { height: 32 });
        } catch(e) { 
          doc.fontSize(14).font('Helvetica-Bold').fillColor('#001b70').text('EGSPGOI', 50, 45);
        }
        
        // Right Text Logo
        doc.fontSize(18).font('Helvetica-Bold').fillColor('#001b70').text('CreditWise', 400, 50, { align: 'right' });
        doc.moveTo(50, 85).lineTo(545, 85).strokeColor('#e2e8f0').lineWidth(1.5).stroke();
      };

      drawHeader();
      doc.y = 105;

      // --- Title & Stats ---
      doc.fillColor('#1a202c').fontSize(16).font('Helvetica-Bold').text(metadata.title);
      doc.fontSize(10).font('Helvetica').fillColor('#4a5568').text(`Aggregation Scope: ${metadata.level.toUpperCase()} | Generated By: ${metadata.generatedBy}`);
      doc.moveDown(1.5);

      // Summary Panel
      const totalPoints = data.reduce((sum, item) => sum + (item.points || 0), 0);
      const startStatsY = doc.y;
      doc.rect(50, startStatsY, 495, 55).fillAndStroke('#f8fafc', '#e2e8f0');
      doc.fillColor('#2d3748').fontSize(10);
      
      doc.font('Helvetica-Bold').text('Total Activities:', 70, startStatsY + 15);
      doc.font('Helvetica').text(`${data.length}`, 160, startStatsY + 15);
      
      doc.font('Helvetica-Bold').text('Cumulative Points:', 70, startStatsY + 32);
      doc.font('Helvetica').text(`${totalPoints}`, 160, startStatsY + 32);

      doc.font('Helvetica-Bold').text('Positive Credits:', 280, startStatsY + 15);
      doc.font('Helvetica').text(`${data.filter(c => c.type === 'positive').length}`, 380, startStatsY + 15);

      doc.font('Helvetica-Bold').text('Negative Credits:', 280, startStatsY + 32);
      doc.font('Helvetica').text(`${data.filter(c => c.type === 'negative').length}`, 380, startStatsY + 32);
      
      doc.y = startStatsY + 75;

      // --- Table ---
      const colWidths = { date: 60, faculty: 110, activity: 215, type: 60, points: 40 };
      const colPos = { date: 55, faculty: 120, activity: 235, type: 460, points: 515 };

      const drawTableHeader = (y) => {
        doc.rect(50, y, 495, 22).fill('#edf2f7');
        doc.fillColor('#4a5568').fontSize(8.5).font('Helvetica-Bold');
        doc.text('DATE', colPos.date, y + 7);
        doc.text('FACULTY & ID', colPos.faculty, y + 7);
        doc.text('ACTIVITY DESCRIPTION', colPos.activity, y + 7);
        doc.text('TYPE', colPos.type, y + 7);
        doc.text('PTS', colPos.points, y + 7);
      };

      drawTableHeader(doc.y);
      let rowY = doc.y + 27;

      data.forEach((item, index) => {
        const facultyText = `${item.facultySnapshot?.name || 'N/A'}\n(${item.facultySnapshot?.facultyID || 'N/A'})`;
        const activityText = item.title || 'N/A';
        
        // Calculate row height based on content to prevent overlap
        const fHeight = doc.heightOfString(facultyText, { width: colWidths.faculty });
        const aHeight = doc.heightOfString(activityText, { width: colWidths.activity });
        const rowHeight = Math.max(35, fHeight + 10, aHeight + 10);

        if (rowY + rowHeight > 730) { // Check if row will exceed page bottom (approx 730 for A4 with 50 margin)
          doc.addPage();
          drawHeader();
          drawTableHeader(105);
          rowY = 135; // Reset rowY for new page, below header and table header
        }

        // Background for zebra effect
        if (index % 2 !== 0) {
          doc.rect(50, rowY - 5, 495, rowHeight).fill('#fafafa');
        }

        doc.fillColor('#2d3748').font('Helvetica').fontSize(8);
        
        // Date
        doc.text(new Date(item.createdAt).toLocaleDateString(), colPos.date, rowY);
        
        // Faculty (ID)
        doc.text(facultyText, colPos.faculty, rowY, { width: colWidths.faculty });
        
        // Activity
        doc.text(activityText, colPos.activity, rowY, { width: colWidths.activity, align: 'justify' });
        
        // Type
        const typeColor = item.type === 'positive' ? '#166534' : '#991b1b';
        doc.fillColor(typeColor).font('Helvetica-Bold').text(item.type?.toUpperCase() || 'N/A', colPos.type, rowY);
        
        // Points
        doc.fillColor('#1a202c').text(String(item.points || 0), colPos.points, rowY, { width: colWidths.points, align: 'center' });

        // Border bottom
        doc.moveTo(50, rowY + rowHeight - 5).lineTo(545, rowY + rowHeight - 5).strokeColor('#f1f5f9').lineWidth(0.5).stroke();

        rowY += rowHeight;
      });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Generate HTML Report (Landing Page)
 * @param {Array} data - Array of credit objects
 * @param {Object} metadata - { level, title, date }
 * @param {Object} links - { pdf, excel }
 * @returns {string} - HTML string
 */
function createHtmlReport(data, metadata, links) {
  const rows = data.map(item => `
    <tr>
      <td>${new Date(item.createdAt).toLocaleDateString()}</td>
      <td>${item.facultySnapshot?.name || 'N/A'}<br><small>${item.facultySnapshot?.facultyID || 'N/A'}</small></td>
      <td>${item.title || 'N/A'}</td>
      <td class="type-${item.type}">${item.type?.toUpperCase() || 'N/A'}</td>
      <td><strong>${item.points || 0}</strong></td>
      <td><span class="status-${item.status}">${item.status?.toUpperCase() || 'N/A'}</span></td>
    </tr>
  `).join('');

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${metadata.title}</title>
      <style>
        body { font-family: 'Inter', system-ui, -apple-system, sans-serif; line-height: 1.5; color: #1a202c; background: #f7fafc; margin: 0; padding: 2rem; }
        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 2rem; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }
        header { border-bottom: 2px solid #edf2f7; margin-bottom: 2rem; padding-bottom: 1rem; display: flex; justify-content: space-between; align-items: flex-end; }
        h1 { margin: 0; color: #2d3748; font-size: 1.5rem; }
        .meta { color: #718096; font-size: 0.875rem; }
        .actions { display: flex; gap: 0.75rem; margin-bottom: 1.5rem; }
        .btn { padding: 0.5rem 1rem; border-radius: 6px; text-decoration: none; font-weight: 600; font-size: 0.875rem; transition: all 0.2s; border: 1px solid transparent; }
        .btn-pdf { background: #e53e3e; color: white; }
        .btn-pdf:hover { background: #c53030; }
        .btn-excel { background: #38a169; color: white; }
        .btn-excel:hover { background: #2f855a; }
        table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
        th { text-align: left; background: #edf2f7; padding: 0.75rem; font-size: 0.875rem; text-transform: uppercase; color: #4a5568; }
        td { padding: 10px; border-bottom: 1px solid #edf2f7; font-size: 0.9375rem; }
        .type-positive { color: #38a169; font-weight: bold; }
        .type-negative { color: #e53e3e; font-weight: bold; }
        .status-approved { background: #c6f6d5; color: #22543d; padding: 2px 8px; border-radius: 9999px; font-size: 0.75rem; }
        .status-pending { background: #feebc8; color: #744210; padding: 2px 8px; border-radius: 9999px; font-size: 0.75rem; }
        footer { margin-top: 2rem; text-align: center; color: #a0aec0; font-size: 0.75rem; }
        @media (max-width: 640px) { body { padding: 1rem; } .container { padding: 1rem; } header { flex-direction: column; align-items: flex-start; gap: 1rem; } }
      </style>
    </head>
    <body>
      <div class="container">
        <header>
          <div>
            <h1>${metadata.title}</h1>
            <div class="meta">Level: ${metadata.level} | Generated: ${metadata.date}</div>
          </div>
          <div class="actions">
            <a href="${links.pdf}" class="btn btn-pdf">Download PDF</a>
            <a href="${links.excel}" class="btn btn-excel">Download Excel</a>
          </div>
        </header>
        
        <div style="overflow-x: auto;">
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Faculty</th>
                <th>Activity</th>
                <th>Type</th>
                <th>Pts</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${rows}
            </tbody>
          </table>
        </div>

        <footer>
          This is a live report generated from the Faculty Credit System. 
          The data shown is current as of the time of generation.
        </footer>
      </div>
    </body>
    </html>
  `;
}

module.exports = { createExcelReport, createPdfReport, createHtmlReport };
